name: Terraform Destroy

on:
  workflow_dispatch:   # Run manually only (safe!)
    inputs:
      confirm:
        description: "Type 'DESTROY' to confirm resource deletion"
        required: true

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    if: github.event.inputs.confirm == 'DESTROY'  # Safety check

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3️⃣ Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8  # or latest stable

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./iac

      # 5️⃣ Terraform Destroy (Auto-Approve)
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./iac
